//! Sections 32.3 and 32.4, and the compute path: which bindings a recording
//! actually uses.
//!
//! A shader interface names the slots its stage reads, and a bind group fills
//! every slot its layout declares. The gap between those two is the point:
//! binding ten buffers does not use ten buffers, and a use is generated by the
//! draw or dispatch that references it rather than by `set_bind_group`.

use super::*;
// ---------------------------------------------------------------------------
// Sections 32.3 and 32.4: only referenced bindings are used
// ---------------------------------------------------------------------------

#[test]
fn a_pipeline_reports_only_the_bindings_its_shaders_reference() {
    let mock = Mock::new();
    let (_layout, pipeline) = selective_pipeline(&mock);

    let mut slots: Vec<u32> = pipeline
        .used_bindings()
        .iter()
        .map(|outcome| outcome.slot.get())
        .collect();
    slots.sort_unstable();

    assert_eq!(
        slots,
        vec![0, 1, 2],
        "the layout declares ten slots, and the shaders reference exactly three \
         of them across both stages"
    );
}

#[test]
fn a_draw_contributes_uses_for_only_the_referenced_bindings() {
    let mock = Mock::new();
    let (layout, pipeline) = selective_pipeline(&mock);
    let group = uniform_group(&mock, &layout, 10);
    let view = color_view(&mock);
    let descriptor = one_color_scope(&view);

    let mut recorder = mock.recorder();
    {
        let mut scope = recorder
            .begin_raster(&descriptor)
            .expect("a one-attachment scope opens");
        scope
            .set_pipeline(&pipeline)
            .expect("the pipeline matches the scope's attachment signature");
        scope
            .set_bind_group(BindGroupIndex::new(0), &group, &[])
            .expect("the packet matches the pipeline's layout");
        scope
            .draw(0..3, 0..1)
            .expect("a draw over a bound pipeline is recorded");
        scope.end().expect("the scope closes");
    }
    let work = recorder.finish().expect("the recording finalizes");

    let uniform_reads = work
        .resource_uses()
        .iter()
        .filter(|use_| {
            matches!(use_, ResourceUse::Buffer(use_) if use_.access == AccessMask::UNIFORM_READ)
        })
        .count();
    assert_eq!(
        uniform_reads, 3,
        "ten buffers are bound, but only the three the shaders reference are used"
    );

    let texture_writes = work
        .resource_uses()
        .iter()
        .filter(|use_| {
            matches!(use_, ResourceUse::Texture(use_) if use_.access.contains(AccessMask::COLOR_WRITE))
        })
        .count();
    assert_eq!(texture_writes, 1, "the color attachment is written once");
}

#[test]
fn a_draw_whose_shader_group_is_unbound_is_refused() {
    let mock = Mock::new();
    let (_layout, pipeline) = selective_pipeline(&mock);
    let view = color_view(&mock);
    let descriptor = one_color_scope(&view);

    let mut recorder = mock.recorder();
    {
        let mut scope = recorder
            .begin_raster(&descriptor)
            .expect("a one-attachment scope opens");
        scope.set_pipeline(&pipeline).expect("the pipeline binds");
        let error = scope
            .draw(0..3, 0..1)
            .expect_err("the shader references group 0, which is not bound");
        assert_eq!(error.kind(), RhiErrorKind::InvalidUsage);
        assert_eq!(error.operation(), Some("draw"));
        scope.end().expect("the scope still closes");
    }
    let work = recorder
        .finish()
        .expect("a refused draw leaves the recorder usable");
    assert!(
        work.resource_uses()
            .iter()
            .all(|use_| !matches!(use_, ResourceUse::Buffer(_))),
        "the refused draw contributed no buffer use"
    );
}

// ---------------------------------------------------------------------------
// The compute path
// ---------------------------------------------------------------------------

/// A compute pipeline whose shader reads slot 0 of a one-slot layout.
fn plain_compute_pipeline(mock: &Mock) -> crate::rhi::pipeline::ComputePipeline {
    let compute = shader(
        mock,
        ShaderStage::Compute,
        ShaderInterface::new().with_resource(uniform_requirement(0)),
    );
    let layout = compute_uniform_layout(mock, 1);
    let interface = mock
        .device()
        .create_pipeline_interface(&PipelineInterfaceDescriptor::new(vec![layout]))
        .expect("the mock device accepts a one-group interface");
    mock.device()
        .create_compute_pipeline(&ComputePipelineDescriptor::new(compute, interface))
        .expect("the mock device accepts a compute pipeline")
}

#[test]
fn a_dispatch_declares_compute_work_and_its_binding_uses() {
    let mock = Mock::new();
    let pipeline = plain_compute_pipeline(&mock);
    let layout = compute_uniform_layout(&mock, 1);
    let group = uniform_group(&mock, &layout, 1);

    let mut recorder = mock.recorder();
    {
        let mut scope = recorder
            .begin_compute()
            .expect("the mock device enables the compute feature");
        scope.set_pipeline(&pipeline).expect("the pipeline binds");
        scope
            .set_bind_group(BindGroupIndex::new(0), &group, &[])
            .expect("the packet matches the pipeline's layout");
        scope
            .dispatch(2, 3, 1)
            .expect("a dispatch over a bound pipeline is recorded");
        scope.end().expect("the scope closes");
    }

    let work = recorder.finish().expect("the recording finalizes");
    assert!(work.work_domains().contains(LaneWorkDomains::COMPUTE));
    assert!(
        !work.work_domains().contains(LaneWorkDomains::RASTER),
        "a compute-only recording declares no raster work"
    );
    let uniform_reads = work
        .resource_uses()
        .iter()
        .filter(|use_| {
            matches!(use_, ResourceUse::Buffer(use_) if use_.access == AccessMask::UNIFORM_READ)
        })
        .count();
    assert_eq!(uniform_reads, 1, "the dispatch reads the one bound uniform");
}

#[test]
fn a_dispatch_without_a_bound_pipeline_is_refused() {
    let mock = Mock::new();
    let mut recorder = mock.recorder();

    let mut scope = recorder
        .begin_compute()
        .expect("the mock device enables the compute feature");
    let error = scope
        .dispatch(1, 1, 1)
        .expect_err("a dispatch with no pipeline bound is refused");
    assert_eq!(error.kind(), RhiErrorKind::InvalidUsage);
    assert_eq!(error.operation(), Some("dispatch"));
    scope.end().expect("the scope still closes");
    assert!(!recorder.is_poisoned());
}
